name: '314 Automation Actions'
description: 'Task automations for 314 studio'
inputs:
  m2m-314-automation-secret:
    description: '314 automation api secret.'
    required: true
  m2m-314-automation-base-url:
    description: '314 automation api base url.'
    required: true
  trello-list-name-under-review:
    description: 'Trello list name for cards under review.'
    required: true
  trello-list-name-in-progress:
    description: 'Trello list name for cards done.'
    required: true
  workflow-id:
    description: 'Workflow id'
    required: false
  build-version:
    description: 'Game build version'
    required: false
  build-file-name:
    description: 'Game build file name'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'