name: '314 Automation Actions'
description: 'Attach Pull request and Branch to Trello card.'
inputs:
  m2m-314-automation-secret:
    description: '314 automation api secret.'
    required: true
  m2m-314-automation-base-url:
    description: '314 automation api base url.'
    required: true
  trello-list-name-under-review:
    description: 'Trello list name for cards under review.'
    required: true
  trello-list-name-in-progress:
    description: 'Trello list name for cards done.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'