name: '314 Trello Automation Action'
description: 'Attach Pull request and Branch to Trello card.'
inputs:
  trello-key:
    description: 'Trello auth key'
    required: true
  trello-token:
    description: 'Trello auth token'
    required: true
  trello-api-base:
    description: 'Trello api gateway'
    required: true
  github-repo-token:
    description: 'github token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'