on:
  create:
    branches:
    - RLS-*
  pull_request:
    branches:
    - main

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  attach_pr_to_trello:
    runs-on: ubuntu-latest
    name: Attach GitHub pull request to Trello cards
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Attach PR to Trello
        uses: ./
        id: p2
        with:
          trello-key: ${{ secrets.TRELLO_API_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
          trello-api-base: ${{ vars.TRELLO_API_BASE_URL }}
          github-repo-token: ${{ secrets.GITHUB_TOKEN }}