on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test trello github action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./
        id: test1
        with:
          trello-key: ${{ secrets.TRELLO_API_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
          trello-api-base: ${{ secrets.TRELLO_API_BASE_URL }}