on:
  create:
    branches:
    - RLS-*
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    if: true
    runs-on: ubuntu-latest
    name: Build 314 API services
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: scripts/DeployAPIServices.sh

  314-automation:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Run automation actions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Attach PR to Trello
        uses: ./
        id: s1
        with:
          trello-board-id: ${{ vars.TRELLO_BOARD_ID }}
          trello-list-name-done: ${{ vars.TRELLO_LIST_NAME_DONE }}
          trello-list-name-under-review: ${{ vars.TRELLO_LIST_NAME_UNDER_REVIEW }}
          trello-list-name-in-progress: ${{ vars.TRELLO_LIST_NAME_IN_PROGRESS }}
          trello-key: ${{ secrets.TRELLO_API_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
          trello-api-base: ${{ vars.TRELLO_API_BASE_URL }}
          github-repo-token: ${{ secrets.GITHUB_TOKEN }}