on:
  create:
    branches:
    - RLS-*
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    if: true
    runs-on: ubuntu-latest
    name: Build 314 API services
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.M2M_314_AUTOMATION_SERVER_HOST }}
          username: ${{ secrets.M2M_314_AUTOMATION_SERVER_USERNAME }}
          key: ${{ secrets.M2M_314_AUTOMATION_SERVER_KEY }}
          port: ${{ secrets.M2M_314_AUTOMATION_SERVER_PORT }}
          script: |
            cd /home/${{ secrets.M2M_314_AUTOMATION_SERVER_USERNAME }}/apps/314-automation
            forever start api.314.js
            git pull
            TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}
            TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}
            TRELLO_API_BASE_URL=${{ vars.TRELLO_API_BASE_URL }}
            TRELLO_BOARD_ID=${{ vars.TRELLO_BOARD_ID }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            M2M_314_AUTOMATION_SECRET=${{ secrets.M2M_314_AUTOMATION_SECRET }}
            NODE_ENV=production forever start api.314.js

  task-automation:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Run automation actions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Attach PR to Trello
        uses: ./
        id: j2s2
        with:
          m2m-314-automation-secret: ${{ secrets.M2M_314_AUTOMATION_SECRET }}
          m2m-314-automation-base-url: ${{ secrets.M2M_314_WORKFLOW_URL_BASE }}